import random
import alexandra

app = alexandra.Application()
name_map = {}

frases = {
    "ESTO ES COMO EL AGUA QUE CAE DEL CIELO SIN QUE SEPAMOS POR QUÉ",
    "DESPUÉS DEL AÑO 14 VIENE EL 15",
    "NO HE DORMIDO NADA, NO ME PREGUNTEN DEMASIADO",
    "DIJE QUE BAJARÍA LOS IMPUESTOS Y LOS ESTOY SUBIENDO",
    "LOS CATALANES HACEN COSAS",
    "A VECES ESTAMOS PENSANDO SIEMPRE EN LO MATERIAL, Y A VECES LOS SERES HUMANOS SOMOS SOBRE TODO PERSONAS",
    "LO MÁS IMPORTANTE QUE SE PUEDE HACER POR VOSOTROS ES LO QUE VOSOTROS PODRAÍS HACER POR VOSOTROS",
    "TODO ES FALSO SALVO ALGUNA COSA",
    "A VECES LA MEJOR DECISIÓN ES NO TOMAR NINGUNA DECISIÓN",
    "LA SEGUNDA YA TAL",
    "NI A HITLER NI A STALIN LES HAN NOMBRADO PERSONAS NON GRATAS EN PONTEVEDRA",
    "UNA COSA ES SER SOLIDARIO Y OTRA ES SER SOLIDARIO A CAMBIO DE NADA",
    "¿USTEDES PIENSAN ANTES DE HABLAR O HABLAN TRAS PENSAR?",
    "TENEMOS QUE FABRICAR MÁQUINAS QUE PERMITAN SEGUIR FABRICANDO MÁQUINAS, PORQUE LO QUE NUNCA VA A HACER LA MÁQUINA ES FABRICAR MÁQUINAS A SU VEZ",
    "SOMOS SENTIMIENTOS Y TENEMOS SERES HUMANOS",
    "IT’S VERY DIFICULT TODO ESTO",
    "¿Y LA EUROPEA?",
}

def getRandom():
    global frases
    return random.choice(list(frases))

@app.launch
def launch_handler(item):
    return alexandra.respond(ssml="<speak>"+getRandom()+"</speak>")

@app.intent('rajoy')
def octoalert_intent():
    return alexandra.respond(ssml="<speak>"+getRandom()+"</speak>")

if __name__ == '__main__':
    app.run('0.0.0.0', 9998, debug=True)
